### ISSUE TITLE
sintax error on line 707 of scanjcl.c program

### ISSUE THREAD

**Issue by arsela2018** [MikeFultonDev/JCL2SH#3]
The compilation is generating a CCN3046 "sintax error" in line 707 of scanjcl.c program-> 
KeyValuePair_T* kvp = cur->kvphead;

to eliminate this error, I fixed it adding an->"else {", in line 606 and  other->"}" just before the line 743
 and then the compilation was ok! and it generates the module jcl2sh in the bin directory ,... but
The problem is at execution time of the jcl2sh to generate the shell, it does not do anything!...

jcl2sh <//'IBMUSER.TEST.JCL\(UPDATE\) >./update.sh

do you know, what is happening? or an idea or suggestion to fix this situation?  
Is it correct the sintax of the execution jcl2sh? is it missing something else?
Thanks a lot for your help!

**Comment by ghost** [comment]
What compiler are you using? I didn't get this so I'm wondering if you are either on a newer/older compiler than me?

**Comment by nholuongut** [comment]
Hi @mikefultonbluemix ,

Please advice to me how to fix and run your source code?

Some info for your reference as below:
step 1: clone source and save my server.
step 2: create 2 folder 
- JCL2SH_SOURCE: save source code here
- JCL2SH: empty
step 2: 
cd to the directory (/u/ibmuser/JCL2SH) = /home/JCL2SH_SOURCE
edit setenv.sh to point to the various MVS programs that will be tested, and to specify where your code was copied to
=>export JCL2SH_ROOT=/home/JCL2SH   
step 3: 
create folder bin into folder /home/JCL2SH_SOURCE
step 4:
sh build.sh
 
please see result as below error: 
[root@01 JCL2SH]# sh build.sh 
Build Default Version
gcc: error: unrecognized command line option ‘-Wc,FLAG(I)’
gcc: error: unrecognized command line option ‘-Wc,xplink,gonum,offset,langlvl(extended),list(./)’
gcc: error: unrecognized command line option ‘-Wc,FLAG(I)’
gcc: error: unrecognized command line option ‘-Wc,xplink,gonum,offset,langlvl(extended),list(./)’
gcc: error: unrecognized command line option ‘-Wc,FLAG(I)’
gcc: error: unrecognized command line option ‘-Wc,xplink,gonum,offset,langlvl(extended),list(./)’
gcc: error: unrecognized command line option ‘-Wc,FLAG(I)’
gcc: error: unrecognized command line option ‘-Wc,xplink,gonum,offset,langlvl(extended),list(./)’
gcc: error: unrecognized command line option ‘-Wc,FLAG(I)’
gcc: error: unrecognized command line option ‘-Wc,xplink,gonum,offset,langlvl(extended),list(./)’
gcc: error: jcl2sh.o: No such file or directory
gcc: error: scanjcl.o: No such file or directory
gcc: error: gensh.o: No such file or directory
gcc: error: jclargs.o: No such file or directory
gcc: error: jclmsgs.o: No such file or directory


Please advice to how to run your source and document guilde step by step. Thanks for the support.

Thanks and best regards,
Nho Luong.

**Comment by MikeFultonDev** [comment]
@arsela2018 and @nholuongut apologies for not noticing your issues!

probably way too late now but I've dusted off the code.

I'm now building it with VSCode on my Mac and found a few bugs that were slipping through on z/OS and fixed them.
