### ISSUE TITLE
 segmentation fault for inlineGeneratedSYSIN.jcl sample

### ISSUE THREAD

**Issue by ngokavar** [MikeFultonDev/JCL2SH#7]
% ../bin/jcl2sh --input=./inlineGeneratedSYSIN.jcl --output=./inlineGeneratedSYSIN.jcl.sh
zsh: segmentation fault  ../bin/jcl2sh --input=./inlineGeneratedSYSIN.jcl

**Comment by MikeFultonDev** [comment]
I did fix a couple segfaults recently. Feel free to try again if you want and if still a problem show the JCL you are using.
